management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health,info
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
